"""Bounded generation of offline tools over recorded trajectories."""

from .prototype import (
    ToolGenError,
    ToolGenPrototype,
    execute_generated_tool,
    extract_generated_tool,
    validate_generated_tool,
)
from .orchestration import (
    ToolOrchestrationError,
    bell_active_tcp_min_xy_error_tool_request,
    contact_tool_request,
    contact_tool_spec,
    execute_tool_request,
    execute_tool_spec,
    hammer_left_camera_contact_count_tool_request,
    official_success_tool_request,
    time_to_success_tool_request,
    pickup_to_contact_tool_request,
    pickup_to_contact_tool_spec,
    validate_tool_spec,
)
from .router import (
    ToolRouterError,
    catalog_snapshot,
    route_tool_request,
    validate_tool_request,
)
from .registry import (
    RunLocalRegistryError,
    find_run_local_registration,
    infer_registry_dir,
    load_registry,
    request_candidate_promotion,
)
from .reviewed_registry import (
    ReviewedRegistryError,
    build_review_manifest_template,
    find_reviewed_registration,
    install_reviewed_registration,
    load_reviewed_registry,
    public_reviewed_registration_summary,
    validate_review_manifest,
)
from .targets import (
    BELL_ACTIVE_TCP_MIN_XY_ERROR_METRIC,
    PICKUP_TO_CONTACT_METRIC,
    evaluate_target_oracle,
)
from .metric_spec import (
    MetricSpecError,
    build_task_code_context,
    compile_metric_spec_source,
    evaluate_metric_spec,
    execute_metric_spec,
    metric_spec_tool_spec,
    validate_metric_spec,
)
from .query_induced import query_induced_result_to_tool_execution

__all__ = [
    "ToolGenError",
    "ToolGenPrototype",
    "execute_generated_tool",
    "extract_generated_tool",
    "validate_generated_tool",
    "ToolOrchestrationError",
    "bell_active_tcp_min_xy_error_tool_request",
    "ToolRouterError",
    "RunLocalRegistryError",
    "ReviewedRegistryError",
    "contact_tool_request",
    "contact_tool_spec",
    "execute_tool_request",
    "execute_tool_spec",
    "hammer_left_camera_contact_count_tool_request",
    "official_success_tool_request",
    "time_to_success_tool_request",
    "pickup_to_contact_tool_request",
    "pickup_to_contact_tool_spec",
    "catalog_snapshot",
    "route_tool_request",
    "validate_tool_request",
    "validate_tool_spec",
    "find_run_local_registration",
    "infer_registry_dir",
    "load_registry",
    "request_candidate_promotion",
    "build_review_manifest_template",
    "find_reviewed_registration",
    "install_reviewed_registration",
    "load_reviewed_registry",
    "public_reviewed_registration_summary",
    "validate_review_manifest",
    "PICKUP_TO_CONTACT_METRIC",
    "BELL_ACTIVE_TCP_MIN_XY_ERROR_METRIC",
    "evaluate_target_oracle",
    "MetricSpecError",
    "build_task_code_context",
    "compile_metric_spec_source",
    "evaluate_metric_spec",
    "execute_metric_spec",
    "metric_spec_tool_spec",
    "validate_metric_spec",
    "query_induced_result_to_tool_execution",
]
